export default [
  {
    latest: [
      {
        image: "./crewel.jpg",
        alt: "crewel website",
        title: "Crewel Shopify",
        text: "The project was built with Shopify. The site features dynamic content hosted on Shopify, CSS animations using GSAP, and a basic navigation system.",
        link: "View Project",
        url: "https://www.crewelwork.com/",
      },
      {
        image: "./breakintotech.jpg",
        alt: "break into tech website",
        title: "Break Into Tech Webflow",
        text: "A Webflow project that comprises custom UI components built from the ground up, featuring GSAP animations.",
        link: "View Project",
        url: "https://howtobreakintotech.com/",
      },
      {
        image: "./sellit.jpg",
        alt: "Sellit Custom Dashboard",
        title: "Sellit Website",
        text: "This project features a custom Thinkific dashboard built with HTML, Liquid, and SCSS for Realtor Ryan Serhant from the Netflix hit show Sell It Like Serhant.",
        link: "View Project",
        url: "https://sellit.com/",
      },
      {
        image: "./goodinside.jpg",
        alt: "good inside website",
        title: "Good Inside Website",
        text: "The project was built using Next.js, integrated with Headless WordPress as the CMS, and Laravel for the back-end, providing a robust, scalable architecture",
        link: "View Project",
        url: "https://www.goodinside.com/",
      },
      {
        image: "./missexcel.jpg",
        alt: "miss excel website",
        title: "Miss Excell Website",
        text: "The project was developed using Thinkific as the platform, with custom styling implemented through CSS, dynamic animations powered by GSAP, and Liquid templating to enable flexible content management and customization.",
        link: "View Project",
        url: "https://www.miss-excel.com/",
      },
      {
        image: "./tyllr.jpg",
        alt: "tyllr website",
        title: "Tyllr Website",
        text: "The project was developed using Builder.io and Next.js for a fast, server-rendered front-end. Tailwind CSS was used for responsive and efficient styling, while GSAP animations added dynamic, engaging visual effects.",
        link: "View Project",
        url: "https://tyllr.co/",
      },
      {
        image: "./sts.jpg",
        alt: "salary transparent street website",
        title: "Salary Transparent Street Website",
        text: "The project was developed using Next.js, server-side rendered front-end, Strapi as a headless CMS, and Tailwind CSS for streamlined, responsive styling throughout the site.",
        link: "View Project",
        url: "https://www.salarytransparentstreet.com/",
      },
      {
        image: "./wobo.jpg",
        alt: "wobo website",
        title: "Wobo Marketing Website",
        text: "The marketing site was built using Next.js to ensure fast, server-rendered performance, with custom styling applied through CSS, and engaging, interactive elements brought to life using GSAP animations and Swiper.js.",
        link: "View Project",
        url: "https://wobo.app/",
      },
    ],
    old: [
      {
        image: "./orderin-website.jpg",
        alt: "orderin website",
        title: "Orderin Website",
        text: "The project was bootstrapped with next.js. The site features dynamic content hosted on Storyblok CMS, CSS animations with the intersection observer and a complex navigation system.",
        link: "View Project",
        url: "",
      },
      {
        image: "./orderin-elements.jpg",
        alt: "orderin design system",
        title: "Orderin Design System",
        text: "A next.js project which comprises of custom UI components built from the ground up.  The project has a documentation site that showcases the components. This project is still under development.",
        link: "View Project",
        url: "",
      },
      {
        image: "./codilation.jpg",
        alt: "codilation website",
        title: "Codilation Website",
        text: "Project bootstrapped with next.js. This is a personal project for a company which my colleagues and I are growing organically. This project is still under development.",
        link: "View Project",
        url: "",
      },
      {
        image: "./kyc.jpg",
        alt: "knysna yacht company website",
        title: "Knysna Yacht Co.",
        text: "Wordpress project bootstrapped with a basic Wordpress installation dockerized starter theme and ACF to customise the backend. PostCSS for styling and intersection observer for animations.",
        link: "View Project",
        url: "https://knysnayachtco.com/",
      },
      {
        image: "./rockwood.jpg",
        alt: "rockwood website",
        title: "Rockwood Conservation",
        text: "Wordpress project bootstrapped with a basic Wordpress installation dockerized starter theme and ACF to customise the backend. PostCSS for styling and intersection observer for animations.",
        link: "View Project",
        url: "http://www.rockwood.dev.magneticcreative.co.za",
      },
      {
        image: "./is3.jpg",
        alt: "is3 website",
        title: "IS3 Website",
        text: "Wordpress project bootstrapped with a basic Wordpress installation dockerized starter theme and ACF Blocks to customise the backend. PostCSS for styling.",
        link: "View Project",
        url: "http://www.is3.dev.magneticcreative.co.za",
      },
      {
        image: "./zierpools.jpg",
        alt: "zierpools website",
        title: "Zierpools Website",
        text: "A project from our US office. Wordpress bootstrapped with a basic Wordpress installation dockerized starter theme and ACF to customise the backend. PostCSS for styling and intersection observer for animations.",
        link: "View Project",
        url: "https://www.zierpools.com",
      },
      {
        image: "./meyerbros.jpg",
        alt: "MeyerBros Website",
        title: "MeyerBros Website",
        text: "Wordpress project bootstrapped with a basic Wordpress installation dockerized starter theme and ACF to customise the backend. PostCSS for styling and intersection observer for animations. Co-designed this project on Abobe XD.",
        link: "View Project",
        url: "http://www.meyerbros.co.za",
      },
      {
        image: "./cemforce.jpg",
        alt: "Cemforce Website",
        title: "Cemforce Website",
        text: "Wordpress project bootstrapped with a basic Wordpress installation dockerized starter theme and ACF to customise the backend. PostCSS for styling and intersection observer for animations.",
        link: "View Project",
        url: "http://www.cemforce.dev.magneticcreative.co.za",
      },
      {
        image: "./element8.jpg",
        alt: "element 8 Website",
        title: "Element8 Website",
        text: "Wordpress project bootstrapped with a basic Wordpress installation dockerized starter theme and ACF to customise the backend. PostCSS for styling and intersection observer for animations.",
        link: "View Project",
        url: "http://www.element8.co.za",
      },
      {
        image: "./liege.jpg",
        alt: "liege africa",
        title: "Liege Africa Website",
        text: "Wordpress project bootstrapped with a basic Wordpress installation dockerized starter theme and ACF to customise the backend. PostCSS for styling and intersection observer for animations. Co-designed this project on Abobe XD.",
        link: "View Project",
        url: "",
      },
      {
        image: "./avula.jpg",
        alt: "avula safaris",
        title: "Avula Safaris Website",
        text: "Wordpress project bootstrapped with a basic Wordpress installation dockerized starter theme and ACF to customise the backend. PostCSS for styling.",
        link: "View Project",
        url: "",
      },
    ],
  },
];
